### PR TITLE
Added shortlist binary files for all 5 language directions

### PR DESCRIPTION
**Pull request by abhi-agg**
This PR:
1. Adds binary version of lexical shortlist files in `prod` folder
    1. The README changes details the instructions on how these binary files were generated from source (lex.*.s2t.gz)
    2. The current setting for binary shortlist is 50 (firstNum) 50 (bestNum) 0 (threshold), which is consistent with [browsermt/students](https://github.com/browsermt/students/blob/master/binary_shortlist.sh#L18)
2. Moved the lex.*.s2t.gz files from `prod` to `dev` folder
    1. They are single source of truth from which bin versions are generated, so we should not remove them from repo

Merging this PR will allow users to run wasm test page of https://github.com/browsermt/bergamot-translator to perform inference using models and shortlist bytes (instead of files).

### CODE REVIEW

**Review by evgenyrp — CHANGES_REQUESTED** [review]
@abhi-agg please provide more context about those binary shortlists. 

What are the differences with current lex.*.s2t.gz files? Is it the same thing just encoded differently? If yes please provide instructions in readme how to convert regular shortlist to a binary version. 

Can we remove old shortlists or we still need them for backward compatibility with previous version of the extension?

**Comment by evgenyrp** [comment]
it duplicates this PR btw https://github.com/mozilla-applied-ml/bergamot-models/pull/12/files It also clarifies how to convert shortlists.

**Comment by abhi-agg** [comment]
> @abhi-agg please provide more context about those binary shortlists.
 
Updated the comment above.

> What are the differences with current lex.*.s2t.gz files? Is it the same thing just encoded differently? If yes please provide instructions in readme how to convert regular shortlist to a binary version.
> 

The current lex.*.s2t.gz files are just text files while the generated files are binary version. Added README changes in this PR to reflect this 👍 


> Can we remove old shortlists or we still need them for backward compatibility with previous version of the extension?

We should move them to `dev` folder and not remove them from this repo because they still are the single source of truth from where the bin versions are generated. I will move them from `prod` to `dev` 👍

**Comment by abhi-agg** [comment]
> it duplicates this PR btw https://github.com/mozilla-applied-ml/bergamot-models/pull/12/files It also clarifies how to convert shortlists.

Damn. This was a miss. It would have saved me effort on this PR. Although, I would still have to provide a minor fix on naming convention used for bin files there. In any case, we will discard that one.

**Review by motin — APPROVED** [review]

**Comment by abhi-agg** [comment]
As all comments from @eu9ene are addressed, I am merging it now.

**Pull request merged**
