### PR TITLE
Folder restructure

### PR DESCRIPTION
**Pull request by andrenatal**
Separating the structure of the repo in two folders: `dev` and `prod` -- the former contains models we are not shipping, and the latter the opposite.

### CODE REVIEW

**Review by motin — CHANGES_REQUESTED** [review]
We need to make two changes before merging this:
1. Dev and prod folders should ideally have the same sub-structure. Currently dev has `dev/language-pair/type-of-file/file.ext` and prod has `prod/language-pair/file.ext`, eg missing the type-of-file folder level.
2. The deen vocab file should be in prod, since it is used also for ende translation, which is prod-level.
@abhi-agg feel free to restructure this and push to the same PR branch.

**Comment by andrenatal** [comment]
@motin I think is fine to have all models per language pair in a single folder inside `prod` since they all differ and you need to ship all them together, and while the models in the `dev` folder are all the same but just compiled differently (int and fp32). I think in the end it all boils down to how you load in the extension. Maybe you and @abhi-agg can reach an agreement here and have this settled and being properly packaged and loaded in the extension.

**Comment by motin** [comment]
Yes, I am fine with @abhi-agg amending this PR in the way he sees fit. Point 1 is not a must, it is just nice and clear to keep similar folder structures, even though obviously the extension can adapt to either structure. Point 2 is a must to be able to use the ende model in prod.

**Comment by abhi-agg** [comment]
I propose the following folder structure:

`prod/<language-pair>/<all-files-of-language-pair>`
`dev/<language-pair>/<all-files-of-language-pair>`

Examples:
`prod/esen/model.esen.intgemm.*`
`prod/esen/vocab.esen.spm.gz`

`dev/esen/model.esen.*`
`dev/esen/vocab.esen.spm.gz`


PS: vocab files will be replicated in both `prod` and `dev` but we can afford that because they are < 500 KB in size. Additionally, this will not be duplicated in packaging if we package either `dev` or `prod`, so we are fine 👍

**Comment by abhi-agg** [comment]
@motin Could you please review?

Right now, only the `prod` folder is complete in itself. `dev` folder is incomplete (misses the lexical shortlist files + vocab files). We will fix the `dev` folder later.

**Review by motin — APPROVED** [review]

**Pull request merged**
