### PR TITLE
Add models for English -> German; Estonian <-> English + Rename files + Gzip files

### LINKED ISSUE #1: Check if the en<>es models match
Hi @abhi-agg , could you please check (using CRC) if these models in the `enes`and `esen` folders match the models you used to built the artifacts on Friday, please? If not, could you please push and update them here. I used the ones from the rest server but I don't know if they match the ones you used.

Thanks

### PR DESCRIPTION
**Pull request by motin**
Also gzipped all model files so that disk space is saved for all consumers
All files have been re-imported from the [students repo](https://github.com/browsermt/students) to make sure the correct model files are included. 
Files have been renamed to have consistent naming that matches the extension integration (https://github.com/mozilla-extensions/bergamot-browser-extension/pull/22).
Fixes #1

### CODE REVIEW

**Review by abhi-agg — CHANGES_REQUESTED** [review]
I believe this is a mistake:
esen/lex.s2t → ende/model.ende.npz.gz
enes/lex.s2t → eten/model.eten.npz.gz

**Comment by motin** [comment]
> I believe this is a mistake:
> esen/lex.s2t → ende/model.ende.npz.gz
> enes/lex.s2t → eten/model.eten.npz.gz

This is a bug in git/github. As seen on the Files changed tab, all files are seen as "Empty file. ", probably because they are so large and contain binary content. Thus, we can safely ignore the faulty results of git's/github's renaming heuristics. 

To be sure, feel free to gunzip and checksum all files / compare them to the corresponding files in https://github.com/browsermt/students

**Comment by abhi-agg** [comment]
> As seen on the Files changed tab, all files are seen as "Empty file. ", probably because they are so large and contain binary content. 

@motin For the files that are newly added, it shows "Empty file". However, my concern is that, github shows that, files that already exist in this repo are renamed to something else (like for this one : `enes/model.enes.npz → esen/model.esen.npz.gz`)

I am not sure whether this is something github is doing or this is genuinely a mistake.

**Comment by motin** [comment]
> @motin For the files that are newly added, it shows "Empty file". However, my concern is that, github shows that, files that already exist in this repo are renamed to something else (like for this one : `enes/model.enes.npz → esen/model.esen.npz.gz`)
> 
> I am not sure whether this is something github is doing or this is genuinely a mistake.

Yes, this is the same github bug. When all files are seen as empty files, git's/github's renaming heuristics go haywire. If you are uncertain, check out this branch and check the files.

**Comment by abhi-agg** [comment]
Okay. Let's merge it and perform the CRC check.

**Review by abhi-agg — APPROVED** [review]

**Pull request merged**
