### PR TITLE
Add missing vocabularies to make prod models directories self-sufficient

### PR DESCRIPTION
**Pull request by evgenyrp**
Added missing vocabularies to make prod models directories self-sufficient.

### CODE REVIEW

**Review by motin — APPROVED** [review]
This increases the current .data bundle size with about 0.8mb. Not much in comparison to the existing size (huge) but worth noting here (noted as of this comment). 

The context of this PR is that it would make sense to duplicate to make content of every folder self-sufficient because any language pair can be retrained separately using any other vocab. Also if some pairs are incomplete, they should not be present in prod folder. Then we’ll be able to automatically read it and enumerate all the folders + it will be more clear for repo users what is done at this point.

PR approved in the light of this context, as long as we remember to document that some files are indeed identical, and that we deduplicate at some other level (eg checking file hashes during model downloading by the extension to avoid needing to download identical files).

**Comment by abhi-agg** [comment]
@eu9ene Now that every language pair is self-sufficient, I noticed an inconsistency with the names of the files.

e.g.`enes` folder will have vocabulary file with name `vocab.esen.spm`. This sounds inconsistent with other files (`lex.enes.s2t.gz` and `model.enes.intgemm.alphas.bin.gz`) in the same folder where the language pair identifier `enes` is included in their names. This might be confusing to people (might also be interpreted as a mistake)?

2 options:

1. Either we remove the language identifier from all the file names (e.g. just keep the file names as `vocab.spm`, `lex.s2t.gz` and `model.intgemm.alphas.bin.gz`)
2. Or, make the name of vocab file consistent with other files of a folder.

I am fine with any option (2nd one sounds easier to me). Let's all agree and make a final change 👍 

PS: This change might have an impact on bergamot-translator [test app](https://github.com/mozilla/bergamot-translator/blob/main/wasm/test_page/bergamot.html#L76-L95) as well as extension that uses the prod models.

**Comment by evgenyrp** [comment]
@abhi-agg  I also encountered this inconsistency in evaluation scripts and thought about renaming, but now I'm thinking that it is actually useful to specify how this spm vocab was obtained. You can see here that it is created as a part of src->trg training pipeline https://github.com/browsermt/students/blob/master/train-student/data/create-spm-vocab.sh. I assume that training of trg->src language pair might use a different model, corpus or training technique and that vocab might be different. In this case, explicitly specifying the source of this vocab we understand where it was copied from and in case it should be different for opposite language pair it will be easy to catch this error. What are your thoughts?

**Comment by abhi-agg** [comment]
> I assume that training of trg->src language pair might use a different model, corpus or training technique and that vocab might be different. In this case, explicitly specifying the source of this vocab we understand where it was copied from and in case it should be different for opposite language pair it will be easy to catch this error. What are your thoughts?


@eu9ene I agree. May be renaming vocab.ende.spm to vocab.deen.spm is a bad idea. I am fine with the current state of this repo (i.e. we can ignore my [comment](https://github.com/mozilla-applied-ml/bergamot-models/pull/11#issuecomment-805621939)) if that's what you meant or are you proposing something else?

Btw, where are [these data files](https://github.com/browsermt/students/blob/master/train-student/data/create-spm-vocab.sh#L8-L9) coming from? Do you know? Looks like they are the ones that being used to generate vocab files.

**Comment by evgenyrp** [comment]
> are you proposing something else?
For now I propose to leave it as is. Later if we'll see that vocab is always the same for parallel lang pairs we might consider to move them to a separate folder and reuse, but I wouldn't limit training with this assumption.

> where are these data files coming from?
This is training data, it is coming from the previous corspus cleaning step. Yes, vocab is generated based on a sample from training data.

**Comment by abhi-agg** [comment]
Ok. Thanks. Approving it. Let's go with the current setup 👍

**Review by abhi-agg — APPROVED** [review]

**Pull request merged**
